//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCodeFirst_Raihan.Models 
{
    using MvcCodeFirst_Raihan.CustomAttribute;
    using MvcCodeFirst_Raihan.CustomValidation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Teacher
    {
        public int TeacherID { get; set; }

       [Required(ErrorMessage ="This Field Must be Field")]
        [StringLength(40, MinimumLength = 2, ErrorMessage = "Enter Minimum 2 or maximum 40 chacacter !!")]
        [Display(Name = "Teacher Name", Description = "Name of the Teacher")]

        public string TeacherName { get; set; }

        [Required(ErrorMessage = "This Field Must be Field")]
        public string Email { get; set; }

        [Required(ErrorMessage = "This Field Must be Field")]
        //[MyAttribute]
        public int Phone { get; set; }
        [Required(ErrorMessage = "This Field Must be Field")]
        [Range(25, 60, ErrorMessage = "Age Must be between 25 to 60")]
      
        public int Age { get; set; }
        [Required(ErrorMessage = "This Field Must be Field")]
        [CustomHireDate(ErrorMessage = "Hire Date must be less than or equal to Today's Date")]
        [Display(Name = "Joining Date ")]
        [DataType(DataType.Date)]
        public DateTime JoiningDate { get; set; }

        public string ImagePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
